### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by petobens** [kmnk/gitn#9]
I asked Shougo about a denite source similar to fzf's `:Commits` and he suggested using this one.
However I tried running `Denite  gitn_log` inside a git repo and there is no output. 
Am I doing something wrong? Is this source still maintained? Thanks in advance!

**Comment by petobens** [comment]
Ok. I managed to get it to work with the following mappings:
```
nnoremap <silent> <Leader>gl :Denite -auto-preview -default-action=diff
            \ gitn_log:*<CR>
nnoremap <silent> <Leader>gL :execute 'Denite -auto-preview -default-action=diff
            \ gitn_log:' . expand('%:p')<CR>
```
I have a few questions though:
i) Is possible to add a preview of each commit?
ii) When using diff as default action the diff is opened in new tab. Can I open it in a buffer instead of a tab?

Thanks once again :)

**Comment by kmnk** [comment]
Thank you for Questions.

> i) Is possible to add a preview of each commit?

No, it is not implemented yet.
`--auto-preview` option is simply run `preview` action.  
So, it is possible, if I (or someone ?) implement `preview` action on [gitn_log kind](https://github.com/kmnk/gitn/blob/e4cce53a15e84ac80d76adce17b12cdec12948ca/rplugin/python3/denite/kind/gitn_log.py) . 

But gitn has no caching logic ( because I implement very simply logic yet :P ), so (maybe) should implement improving performance logic if use with `--auto-preview` option. 

> ii) When using diff as default action the diff is opened in new tab. Can I open it in a buffer instead of a tab?

`buffer` is meant current buffer ?
It is implemented internally, but was not working as I prefer.
Then pass fixed option value ( [this line](https://github.com/kmnk/gitn/blob/e4cce53a15e84ac80d76adce17b12cdec12948ca/rplugin/python3/denite/kind/gitn_log.py#L89) ).
I can provide it to Denite command option for testing. Wait a while.

Any question ?

**Comment by kmnk** [comment]
Parameter of opening diff method on gitn_log is added by [this commit](https://github.com/kmnk/gitn/commit/f2e92d1237beadf9eab67cbba6efa62c1430a7b6) .

**Comment by petobens** [comment]
> Parameter of opening diff method on gitn_log is added by this commit .

Awesome. Thank you very much!

> So, it is possible, if I (or someone ?) implement preview action on gitn_log kind .

So you actually plan to implement it? Or not for the time being?

**Comment by kmnk** [comment]
> So you actually plan to implement it? Or not for the time being?

My current motivation ( haven't commit recently .. :cry: ) is replacing all source and kind of [vim-unite-giti](https://github.com/kmnk/vim-unite-giti) by `gitn`s that.

But only implementing `preview` action (without improving performance) is not difficult. ... Maybe!

So I implement `preview` action on `gitn_log` kind next.
( Please wait for that without a lot of expectations, I love lazy time :P )

**Comment by petobens** [comment]
Excellent! Thank you once again :)

**Comment by kmnk** [comment]
Preview action to gitn_log kind was added by [this commit](https://github.com/kmnk/gitn/commit/a4f9de144764cc592b54124fde5ce21f639f26b7) .

You can use `-auto-preview` option too :)
